### ISSUE TITLE
Handle empty values actors

### ISSUE THREAD

**Issue by rasvaan** [Rijksmuseum/conversion_oai_formats#2]
Thierry:
In some records, we find wrong <lido:actor> elements built with only an empty <lido:vitalDatesActor> element and no <lido:nameActorSet>

```
<lido:eventActor>
  <lido:actorInRole>
    <lido:actor lido:type="http://terminology.lido-schema.org/actor_type/person">
      <lido:vitalDatesActor/>
    </lido:actor>
    <lido:roleActor/>
  </lido:actorInRole>
</lido:eventActor>
```

This raises an error because <lido:nameActorSet> element is compulsory into a <lido:actor> element.

Depending on what is really expected, two solutions may correct this error:
-	Deletion of the whole <lido:eventActor> element which brings no information
OR
-	Specification of an anonymous actor like this:

```
<lido:eventActor>
  <lido:actorInRole>
     <lido:actor lido:type="http://terminology.lido-schema.org/actor_type/person">
      <lido:nameActorSet>
        <lido:appellationValue xml:lang=”nl”>
          anoniem
        </lido:appellationValue>
      </lido:nameActorSet>
      <lido:vitalDatesActor/>
    </lido:actor>
  <lido:roleActor/>
  </lido:actorInRole>
</lido:eventActor>
```

See records :
AK-RAK-1991-15 and AK-RAK-1992-6. For these two records, the wrong <lido:actor> element is the only one associated to the record.

For other records, this empty <lido:actor> element is not the only one associated to the record, we also find another <lido:actor> which is correctly built (for instance, record BK-NM-11086 associated to Abraham van Aardenberg).
See records : BK-NM-11086, BK-NM-11430-98, BK-NM-10436, BK-NM-11430-87, BK-NM-11430-93, BK-NM-11480-84, BK-NM-11182, BK-NM-11430-96, BK-NM-11430-115, BK-NM-11430-94, BK-NM-9690, BK-NM-11430-97, BK-NM-10437, BK-NM-11430-89, BK-NM-11430-86.

Todo:
- [x] correct Maker 'empty' Online rank 'Other' records @Trineke
- [x] add anonymous to records AK-RAK-1991-15 and AK-RAK-1992-6 @Trineke
- [x] correctly handle missing values, do not add eventActor/vitalDatesActor/etc. if no information available @rasvaan

**Comment by Trineke** [comment]
@rasvaan Checkboxes are not working for me. Todo 1+2 have been solved.

**Comment by rasvaan** [comment]
@rasvaan put the first two points on data cleaning board, to fix for the complete collection.

**Comment by rasvaan** [comment]
Add that the roles of actors are added based on the presence of an identifier for the role, added in: https://github.com/Rijksmuseum/conversion_oai_formats/issues/8
